# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 07:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Imobiliaria', '0002_auto_20170522_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitacao',
            name='proprietario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Proprietário'),
        ),
        migrations.AlterField(
            model_name='juridica',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('sol', 'solteiro'), ('cas', 'casado'), ('div', 'divorciado'), ('sep', 'separado'), ('dis', 'disquitado'), ('ou', 'Outros')], help_text='Estado Civil do Responsável', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='data',
            field=models.DateField(default=datetime.datetime(2017, 5, 22, 7, 53, 24, 448978), help_text='dd/mm/aaa', verbose_name='Data'),
        ),
    ]
