# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 09:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Imobiliaria', '0003_auto_20170522_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitacao',
            name='email',
            field=models.EmailField(blank=True, help_text='exemplo@email.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='capitacao',
            name='telefone',
            field=models.CharField(blank=True, help_text='(DDD)99999-9999', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fisica',
            name='cpf',
            field=models.BigIntegerField(help_text='Somente Números', null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='fisica',
            name='rg',
            field=models.BigIntegerField(blank=True, help_text='Somente Números', max_length=30, null=True, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='telefone_celular',
            field=models.CharField(blank=True, help_text='(DDD)9-99999-9999', max_length=50, null=True, verbose_name='Telefone Celular'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='telefone_comercial',
            field=models.CharField(blank=True, help_text='(DDD)9999-9999', max_length=50, null=True, verbose_name='Telefone Comercial'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='data',
            field=models.DateField(default=datetime.datetime(2017, 5, 22, 9, 26, 12, 830337), help_text='dd/mm/aaa', verbose_name='Data'),
        ),
    ]
