# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Imobiliaria', '0004_auto_20170522_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casa',
            name='numero_matricula',
        ),
        migrations.AddField(
            model_name='casa',
            name='numero_matricola',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número da Matrícola'),
        ),
        migrations.AlterField(
            model_name='casa',
            name='piscina_privativa',
            field=models.BooleanField(verbose_name='Piscina Privativa'),
        ),
        migrations.AlterField(
            model_name='fisica',
            name='rg',
            field=models.BigIntegerField(blank=True, help_text='Somente Números', null=True, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='data',
            field=models.DateField(default=django.utils.timezone.now, help_text='dd/mm/aaa', verbose_name='Data'),
        ),
    ]
